### ISSUE TITLE
QA_Forced Vibration of Single Degree of Freedom System_Introduction_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#77] opened 2016-04-21 08:46 UTC
Defect Description :
In the Introduction page of "Forced Vibration of Single Degree of Freedom System" experiment, when we click on the Damped Free Vibration link it is redirecting to a blank page instead it should redirect to a new tab with the selected link displayed on the screen

Actual Result :
In the Introduction page of "Forced Vibration of Single Degree of Freedom System" experiment, when we click on the Damped Free Vibration link it is redirecting to a blank page 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Forced%20Vibration%20of%20Single%20Degr/Forced%20Vibration%20of%20Single%20Degr_04_Introduction_p1.org

Attachment:
![sd25](https://cloud.githubusercontent.com/assets/14869397/14703644/a0a35f58-07ce-11e6-8e16-4577bff949bb.png)

**Comment by sadhanareddy** [comment] 2016-06-13 09:08
Flash links are working. After conversion of the experiment to ui-3.0, the link is given in the Experiment tab.

**Comment by BSravanthi** [comment] 2016-06-28 05:15
The above said link is not in Introduction page, where as the link is in the experiment page of Forced Vibration of Single Degree of Freedom System.
As the issue is resolved we are closing this issue.

**Closed by BSravanthi** 2016-06-28 05:15 UTC
Labels: Category: Functionality, Developed by: VLEAD, Release Number: Production, Resolved, Severity: S1, Status: Open
