### ISSUE TITLE
QA_Simple Harmonic Oscillator_Prerequisites_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#91] opened 2016-04-21 08:46 UTC
Defect Description :
In the "Simple Harmonic Oscillator" experiment, the minimum requirement to run the experiment is not displayed in the page instead a page or Scrolling should appear providing information on minimum requirement to run this experiment, information like Bandwidth,Device Resolution,Hardware Configuration and Software Required.

Actual Result :
In the "Simple Harmonic Oscillator" experiment, the minimum requirement to run the experiment is not displayed in the page.   

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Simple%20Harmonic%20Oscillator/Simple%20Harmonic%20Oscillator_18_Prerequisites_p1.org

Attachment:
![sd11](https://cloud.githubusercontent.com/assets/14869397/14703288/cef52ed8-07cc-11e6-97c7-5db3fb4fd120.png)

**Comment by sadhanareddy** [comment] 2016-06-09 11:04
Issue is resolved now. Minimum requirement to run the experiment is given in the pre-requisites tab.

**Comment by BSravanthi** [comment] 2016-06-27 08:18
As the issue is resolved closing the issue.

**Closed by BSravanthi** 2016-06-27 08:18 UTC
Labels: Category: Usability, Developed by: VLEAD, Release Number: Production, Resolved, Severity: S2
